let input =
    """lDDWVvlVVQfDMlWjGJTRjQCgTGLCLj
ZLZpwzLBhwZhSLBsjntGCtgJRjbnJgSG
qppdZzzsdsmZphrNsNwZhllDHLcVVDWFPvFWcWdFlv
ztdhgJDBJghmQtPFQPpmbw
lVlLRcnfllcfVcccGnSQVLcsTPFbpwsPFspTSqmbpswpbF
cCHRGcGcCRGlGrGcVGnrdWHWBDzBNhhQZWWNBhJz
NfnSSQpdnRSSpvWdSsjZDGNDjGDwTGTjHG
wlPzPqzPFbMmqPCFCJmbsjbHLDDHDZjDjbGHsT
gwMlgmtmPcqVVvhVnvcRnn
cBNBBCHhbhNhblBcCCvcBHSwTwDQSqRwDQpDRsjHST
dPmzMVWdmmMnnZJtZVdqjTSrjTjrpQrsTTVwQRSj
qzmZMmdZPtnGqclblGlbGvgBFc
ZfpmNDfRhzbbqDnD
SFtFjTTZVTFvVTjHrsVvqGBJqhnSSnbJznLGJwJq
TjdPPtdMPPWCcZgW
qsbmGCsjHNhmhmhzTDznpnlQZlbWlZ
LTSSfSvggVVgBgfLtvvtTSczzpWnZQZnlnzpBcnWpQWc
FrLvrrrVPgdPftSHHdNsjTHjmGThhm
wGQlMjvMwpvjvZjZTZlWjplWJJTggDTgfCnntPgTJPbtPgSP
qNhJmcVmdJqhHnPnDNtnPDCg
LrrchqhRdLVzRdmhJcFFQWGGMjpGlvZzlQQv
ZqZMbZMfQZptpjlF
PJCggvHlwWHvSSvCJNvSPvDBtFDQThFQjtRQhhFTsVThQtsF
PwWCnBBCClcMMznMdG
rNwwQJrJrnQswrQrRRwCShBSLndZpdnhpGFSdhBp
PvzzWVzbclGFhLFGdZll
VWjPWvbjcVbVcGVzjcgzgwQQRRRrqwRJQwwstCRR
zjBMMzznjbssrBrMBbvHDmrlprlrpwGpwQDV
LhRwPPTLLNRZqScPWPWPTSmQvQQDGGdQHVDlmVpQGD
NtfhNwhLLNwRwRNcTBgnJMCBzsBFjsJfCz
jZjsWNDlPfClfMlM
GjqbVSqjhgvgSVSBCPmMmCmfpwTBfh
nGbjqtqcGzsLDFcJLs
ZQtmZdtdQcLndRncdQQLFjWWDHNPfhpnqhqsHNNDnpHs
TrMBGbJTwwlmDPPPWshWHfJq
wmVzbrwbwvBlBlVGtSVLSdFjdFtdjLVR
LBhZFhRPbbnPddMdPPlD
NQszQNczlCSlJSsg
mwmrVQwpQVWwTlvBpHHHFhZj
pzzDffWpQBzMpHvzMfRnTNhZdrdBcnLrcdrTLZ
msgJgtmbgmqJJcdrGcJjGn
bSVPgwntmVnngQWvWSSMpMMHWH
gmGMDHHdpngdrGmGcwbNCCnNcbbCSLwL
zQPPPffQQlVlsPFQFzQchZZbLZNVcbqbNqbZgq
PRjQzfRgRfjQBTfJQTlPFRHWmmvmWHGWrWvWWtjrdHpD
vfrHfqrLfLwwNHdvnthpnnFFpstn
gWcMclgmcRcWgDMWgBgGGFnntqQnGphdQhtbdFnh
qRWmRDlcDqWBBPwPNrZHrwSHjTfr
HVVbhdCdndhZSShMzRrzSM
qBjWqvtWvDJjTjjGJtJtnqBvZMrgSGZlgfSgSRrMQGQRMgMR
wmwtJsvjtTJwsNnVsHpdnsHdds
FCJNZDMPNCNvzqQJHqzGqv
hwjWcSTHwRpSWnQtGgQgGStgQQ
WpwhRHTRpcLRjwlwwTWBcWdlFbCrsPrrLCMDrZCFsCDPrZPM
DJjjShSGhGDSNdpfrWWcLFzrDWrDlF
wtqZgwMBBPVMCBPQggMwqMMzfLlWrWLLzsWcFzTzVTzLss
tgtwQqZBQQZbBZtPgbHpNJnJShcmJppSHh
tHrWmrdzzdHflmHmHrSmqswlqhqNgssMhGgghssn
pJcCBPPQPCcPpRpgwZNZBMnDhMsMBw
RJCvRRVcQpjLpCJPWrftWvSnrFffWbrz
jzlwwzDzTlQftzlWjfrBGBgVHBgpgBtPGVtP
vhsshbMbNhZpgZrrrpHcZr
qhdMqqSLSSbSJMqqSwwjzFzmjFQQFfHzLQ
gDhHNnphPPPNCprHFhHFdbdczzjNqbzjVcdbQTcc
tVJWBtVVZRWtjQbctjqcdj
RfvlGLvLLLlLMZBmZBRhHDVPnVHPHCgFCnhlpn
RFhZFTZvFdjlqqlRNCPwSSPCNPBSwC
spHGswpnWgJLLJCPGg
cWpDrVVbWfWbVfbsdQqcQzjjzlhdwqll
WWJPpQwWdQQPNpQvqlvvCblbvbvwLL
cmRMBMBTbSrTDRMcGBscTGfLZfvfvsCqhLlChZlLhfsC
TVbzGSMGVVgdpdPJpQ
lwsFfsZWGsGmsnlGQcPdBBdMbcPHfcCN
RVvSLtSTrTVrTFPcBdCHRcPHbNNb
LrqzLFTLrgSJLLLtTgJjVJvWlDDnjDWnWWlhlGWGhZWZhn
GQJCMGbrMbbCGrrGtcwhctGjNSvWpVVVRjNJqVqqBBRRJq
ssnglHHsnHzFmHnzHFPVDDSDRgVjvWDNpSSNpB
PZfHmndFzzfPZPZfCdwchwGcbwwhCdMW
DRGVQGmGQVnnGVmnnFpNbzCNRbRttCbpLztC
qdqHBdjTqPlcTchBjJMvvvLtLCcLggLvtmgb
fqhlHjdwqjjJTwldDmDmrGrrWFrDGZwD
wFscLVLrrVhwWgZPrcswgZWFTnQdtTMnpQtjdpqdqvqQMt
JRbHmmbDDSzDmDNpTnBBdpMHQtqtvp
JmCCbvRGzbbGJsLgZsVhgLwwGW
WDQwsBzWbBlMjdVpzTJVMj
fncRngntnPCpJgmdFpFWgm
RGZPZtZCfvWSvRZGSLvPccHwsrHbwHLrwHHQQsBDbllB
PlNZhwgpppccgrqVvttbBfrlls
CznSDDdHDRnRStVsVfDvfrtDZq
QCddZFSFLTmccQmw
rnwfVnclGPPFfSPSqBWZvvBBWqZvqWFh
zLgLQgJssspmQTJmsgjZNmqqzqdHbthDdDDWHbhqBBqb
QgmmjpNgCCZpjJLpmTrfrSrVRPfnrClfPwnS
zDzPPwvwqvPPBqjnqvDqBffSfcSNJpNVfccLLNffBR
MdTMZbgbmmTWGGdmssRCSNsSNVVVcJsNppsC
MJghbhHhbtMMdWhbJhHgdmWvnFzHDQPDjQDvHHwvQwvzwF
gGbqqRDrqDMdcBpVlpMG
WzhPCnWfqMcpBnnNLZ
fCqPHHJCfJhStwhWHbrrgvjFgbQbSbmbQs
fhcchnSpfsNpjVVqnqjrGHqq
zzlFLlPLWdggFqRBjqsrHrBTzz
FDwgFLZWlbbchpwshsCNcw
CmPlqqRJDHRDDsFv
MfSpBQQNNfBfrfVZsmVVdzzrHZmH
QSBSLSgmQBmwPCtgClhjPP
NPNsHHHNsPsvHwDqgpwlqt
rTRWSRrWRzgTzZrRVVLRQzjpbtmmGLlGDDbDwwmtblvDvw
nRzSRrjSVRrnjrgZfrfzNdPdMPBfBMhJhhBcPhcJ
LLhzQSDHDHNpNzHHJBQBMvMBqBRJBBqw
rmbdtmlWCCMnvJrn
FTVdmVgtjdtbWsvjjmdLSDcgHpDzShzDLPLSHh
VFFJQVWHtQVHHWbJRRRHwqPvpMLpLZZWLwlwMllL
jsngsdGssLvlqnZqZw
hhmfDjDsmDNjjNRNVqNVJRtQHJ
jvTnffrgFTwvqMzqGdMMSW
sPbCtCCQQLffZGdWNLWDDzLzGM
PQPBBtfZCZsmJPPplwwmTwpcTcmcgj
NBmBRCCsBTRNTndGdswnlwvwnw
fvbqrbPLqpGwScGGwbbb
HJDPJFJLJtpJHCvCFBBBBNNWvF
HJHgNQJBSlRRbJDRDb
RptsfnshscWMLMZDZp
njmrnPznnsTRTtPzFzRTswgQwqvVVwBNwwvjqCHqHq
CBMgBJCTNgQcsQspPpWjRrWrsWsn
mwLvHLGbdHbGzSHmvmvHzrhjjjPptjWGqZPPZhPRWWGP
vbbrLFwLFDJFDfFN
TnPvZSnQgQPHnnnQvgMSWppWNfWRpWfMtthMNDhN
wLJmLBmGFBFdLBbCBbVCVlsGsWhtHqthRRhqhtHHGqqf
LmHLbCjjBLVZzZSgzQgjrc
wdSwfpBhtFbStpftjSVhBwFrGrsQnQgnGrQmqCPmDrmmDb
zJvzLJLNZNscLzNHHLrGPvGGPrDDqGgDPDgC
RWsNNRMsHTHLHTlMczLHZLWtpFwfpthSjFtwFhjSVplwtj
QbrBDLGGRJMQJQJDbQbGvNscWNnTdvnvtnLcccvl
fqZgpVPZHPmfgPPjBFgcscvNNccdddtdNvdFTs
CgPpghfjjPgVmfBMMCRJQQJzJBwM
jLWDqLdWdwLfHwJwzSSfwS
gCgRRltMrlrCcCMzcBSVfZQfVNZNVSBVNNNh
gMrcPntccGgzgTMlMPrtDWFvLqqdLnDsmLLFFqvp
ttHJNccRRwmnsnHnHWMSwqfgvgfwSQZfQf
ShpLhhzTPBMpQqQgvM
zhbFjVdrjFjVljrVbdPddSTPHNssHnHlRNCHtRtsctJtGsRJ
zMVTscVhQhGGhClv
LfMJmgSBpLRfHmBPgpmJPSBdvQNtlHvrHvNNtNNNClGdGN
JFJmmSFFbFFbRJPBgFPmSBPMzzWWTDjjTsTqqwjVWbjjVVsZ
HZpCnwnggfFggbgLDcTb
SjvWjGzNGGzRjSGmMcLhvhMhFMCcmv
rjrVJNjVrzVNPrwtPwPCHBPB
SWwFbTzsSjPzpjFbsWPTWTcWLCLgLgLBZjGVDjCVBBgCBGCZ
lrJJttQcHqrHrvggHVBgBLffBC
lnhhcqNRJWzhTdsWFz
vzldvzlclbFjFvmtjZ
DDNMNStMsSsGnhSMwQjTQVgVbwMbVTTQ
DsDSCNNGpLtsNLpnNsqLppDzCBcdJHBzllcJfzJBPBdBlR
qWNfDvffbJBFDpNfmpbwhGhwjLgTrGwhbGGwrj
ZctMVCcVVQtTpthlnLtppw
QMcRSPMZcpCZqDFNRFHNJFFF
RmztpGSssNMzJRpCvqsCrqdHCBlBdw
gffPFDcqVbgqWgjlPlwCCrdBdllnBH
cFFZcbcqfQhgbcNJZRSMRtmNJptS
PZthPBWlPNPSPtmHHggFGgBJJbwg
qqzDvLLrfDpvvDLzqvnLzqpzbrCRGJRHwFCmHRwGwgwbbRCj
nnpnMfpMLTVqfmthmsMNSScMhS
dflvbdvpfffzpnNLNbWqtblqHjmVhVRhHrwrwrswhHnjsmwh
gSGMdMcJBgMTGPSPDVZhHhHZmDZhrwwjVm
CPJQGBGGPcSTFcTCScFtLLdWvptWLbNpNzvWQL
WThqhvvRDJDRhwcrscNDNFgDHNct
fnrZVnfVjrSGGLzZbnLzZLjVHstHHHQtgQbPpPcpHsscsFpN
SVjZSzZdndVCdSSZmTRvMWBRWvvWlrvmhJ
BcllhPPmMMBPcbRwgQtgHHgtmwgzmt
rpLqbrbTnNvqjLqLNqrNLvHzDtwpDCzFwggttFFHCQFQ
LrrrNLqjZSTsZZsvjbLjPhcBBlBsBcGPPcPlPVGP
HHhrggvSHDtCDsfF
ZMpLblppNZBDBwLzLLpMssCntfWdCFCnfCCtRNtq
lbmJlzzLMPMmlBzhSJVccSJhTvSTDh
sdjBBFqHscFnHTzCnRSnzgVTlC
LpWWtvZfrpbLpZpWftprLCCNMzCZMmmzTNNTmSSVSM
pLVtrtbGvpbpGLfPddHBscBQJJGcwsQq
hLcLnVVcfQBLZPVZnThfVVmjqjHNjgvNfdvpNdrrvvfp
lbRlWFHJtGNGpqmrqrCN
DzRRDFsbDtFtDJtWRztzJZVBQMhTsLhQZMZHVLcLcP
WgbdmgMmWDDvcPcpbz
jffpllHSpHRptRRGRntSVwvLSCCJDzcCcDLvCzPP
tRFrnlGfZrQpBpgQQsgF
TpbBZbCCHCGZNHbzGqgFdNlcFSdNlStSqg
wvWnWwLCPjJPJhMWtWdMfFSMgcdM
hhmvmJrJLJJJPvvhDjswCRGHHrHzBBHGVRQBzRRQ
zChCSBbpSsQscDHHQh
LNJJRgGltJDvfcrfgHfZ
lJNRGlLnNJtTGVMlFTbwSWqjBbzWWHSW
NDTJQDVwCTCJhVGDLfbBbBfbGqbfHBfBHb
lMgMrggMrmmtzMcgWdlmMlbsRjSRBsTRBWsSHSBTHRBj
cMPlgztzrPMznnMPpgddgdzpwDDNNwhNFCTwNZQFLTVTwV
ZgshQgzQnnwMtDwBwv
SFWFlFZRRcmlWmWRBCDwvwwftBtLmfLf
PjRFdTdWGddrGlPjcsJZpJzTqhzQJzNHhz
PgHQgddszgdGPWpMjljMcj
bSqTqnZLnDJSmnmZmtllGsnVtnWjGGWtjl
fqSLDbRSfBdHsRwsFdHd
RwHWZpCWhHvwvHCBMBpJMJGPJJnJgc
lztljTFljRRBBzBnBMnJMS
QbRljFtQfljbbFqNFrdZVrZfdCCwVwvddH
sHzztVzLTgnssPggHHsnCtzBmfBMrMccBBmqmrBqBCRqMf
ZhDQJhFDqjmSMrRF
dZpwDhNhhZpQJdDQpwnsGttGwLtRRTLRts
QJNhClVgPTTtPNCJJCtJhlNPZZRVZfvfzZzmvvzvsmZsvmzR
blBWBpdbLBDqBpszzffRsvdzjvvd
BLWpqBbqnDHqBbGlnWGBPcPJcHTTPrhtgNtCtgPc
jWVJqVwgsJcHCVlQVVQNBp
vGhGhTPtSSNCddSBCH
ZCCDtbDftZsqrrcnWW
hJThjThhVzVTZZwnNZRdgmzt
lrbSSddsrbPQpsvNtgPRmtHmvtnR
GQrspWdSGbDcsFFLBhCGVBjhjj
rHdlHdZDlTcflcNfcrCgcTWWpWQFsRWsFjRCsCjWCmhF
BnqbvQPLGLBPwqGmsVshsSWShGms
PzzPPQJPMJtJbbznPnDdrHlNldDNltrgtfDg
SmmMQhPSlmTwPpmnpllMSMPrccFDqFrDFGgqrDcCwfDgwq
bVdLLNvdQWVbJbQLVGfGDGfDgrFrqgqJgg
vjjWsbQdBsszhsHlhhPPSHsM
PqzJqNzsJgsgNqPdLJPPPNVpMMVWGlFWNFGMpWppGF
ZnZBjttQZcQZRTQDjQwGFlWMlGdGWVrWWlGn
ZRDBRSZDSdSLsqJHfSbzzL
rljJqtZlJqlJcvBNJBNQfQ
TVMWznvPMTFWznwPFFvwFbbBNBgbcNpQdNcBFQpb
mDnLWsPLvLMnnnmTzLzVCtlRRtjSljCZhDlhtqSq
fgWMHClGMWfgRWWWGCfmfgCSVQNTDFHTtddVQQDZNLDZtVVL
wSqbsvzpwpbpdFTNLQwLNTFN
zscjPnPqsJlmPJCJSC
GZSwQjGwGrCGwrTjdCTwdTBpqqlmNmVpNrNvplJqNNpl
zMfJnDcbRRDRFbzDFRLFBtqNmqqtNBmNBvNm
sHcJRRHzzfQTjjCjQjCH
wJCVVbJgCLCwGsMbbGTlsRWHsztZPZWtPrPrWrHzrz
DBqdvfqDBqFpWZFrtppZJp
djqNfQcjDQjMgbbwLjlJGn
TSwfZMfpQwcCCCCrbbCZ
PLJmGJnjqjrsCjMMVj
LnNNLLLnFFWmLFMGNMDgfRpDQSfwSfgQzBHwTS
CdjNCMmdCrVmCjJdVjFNMtMzhWwpGbpBhPZZZDbGPpDhpr
QSfHzlvgTQffSSHHclgfHnqPbPPPppBhpWDhwWvPhvbwwh
cQfQRgQnQsnsQSgHRQJsCFMsCjLzJJFjCdNC
ltLlJttmQdfVRhNmhB
gWWDrPSvCSWgMMMZBVBdTQPQZNZVPR
vCbwQzcQrCrLFHwJpHHGpp
VbRVvVHRbJVTzVLBVPtt
cSdgSZSZZFhnFcFwdDQcZZhgzpTlzLDzlWTvBWLztBtpLplT
hZZvdrcSZQZSSwncdHCqHmGHqJrCJqbNbq
lwWmsQlDbCZbVWZq
rRShhhhPjTsjTRvHhqfzqfqvBZZvBCZffC
scPThhRSjQmmNpplcg
FChtDTThDqZtjppjvgNvjl
LBwsVdVHLVvvpVGjjgjS
BbHLBfRcsHcBdMbdWJQPWFCQCZZhWrJPQp
zMtWCstzNrQLpbplFwQwhb
gDTDHGvvHVfVdGZVJGDGdnmbwmWFwfhpbnfjwwjpLl
GJcHVJdvZJVGZWHSSvTZMCzrzzRNSBtBNPBMqNBB
pLzZVVGGZmZVlmDsQglgsllc
WSvrjRjrMMFFnFjnrnrdjBRRgdsblQQPbpggsclNDDbPstDs
SMWRBrrrvSRBSSvWWWBTMTCqpZzLCCTCwJZwwzGZzqHL
TvfGwGZpPnSNgSSnGh
srLVHLcjsjVtHqjjrjFjcCqPBggqNQQnMqhgngnznNNB
VtdmPHLmtVHFLdmZWRJlWpWWWlmWfp
SbSbdTsrVrdhfSdDGJWGmNwWWPwTGP
BqlRpBMmllpmnpvvDJPZWPJwZcJgDD
FFRMCnRFtCMRlMplqMBRBppVbtzdrdhssrmHzVVSsVhVHz
dNrhhLsrshSmmRcPhm
WMCngCzCvzvMMpplQvzWlRBPcVStSmTSQbbVSPQmwm
MpzvWnllglJfqfMgsNdZHqNjdDsPHqqZ
rNvGZRsRcRRBtBCttB
DwPPQWnWWnPQnJlPhmTtBFBmqzhpmnFh
QwQQQlbPPMWwDdDwlVDJJPPdvdSjrjdrsgssLLsZLNBrNNNr
VjMMVzngnjQQfJDchZqGNqFPcg
SWBwTtWSFTHwFClHHmwBPcJJDhNGPJNPPhPPGhJt
CBvSBBBWHdmRTvRWRQFLQRnjnfLLzVbs
flSpvLlmZpCpZmVSBtlvHHjFHTdssZdjHFdTWdNh
RmQMQJRQJQmPgrzJrPcRQRJcWdNTGTGGFhGTdFhHThHGMTsF
RzJrqqcqPRqqJDDqttCpmtlwBpDflSLt
hBjPZbPBbWvTRnLRWntD
MNGQNsQwfzsdGfgTGfzQwwffmnCRDVmJLRLCvnvLDvJCDgRL
wTTdFldNHzTMljjFqphrBqhrZb
wDcMCbZbzPDcZDWQdrJLrQrZBLRBQr
FFSHStjtHgllgFdSNmlfFStBqRRssRsRJrLrjrrJBRVhLJ
fGggtfHtgWMwbCGdCT
RQrQDDbVGrRSfbVbGtmGtwHFWsCCzsJSJJHsJPJvWC
hphQnhZQNjlBBcMMpCsHwFjvvHWHWsFvjC
ppcnnBZqllTQfmrffbtGTDGt
dsDFsBZBhCFhshFrpBFnmLQmHmRgRbLqmmmRQDLm
PPBBNNNtGTwJNfTJffNttfLQgqLgHvHbqRwlgmblRvll
NSNTGTJTWPjGWMPSJJzrBSpzdFSddCFdncrs
bPzRlMPTzTMldJMnhswcjzfQVccQhc
HCCqNmNmQQmQssJn
pHptprtgRStTtMJt
nTmhrsPMsTfmHHGcSgtj
bJJwdlrJQLlvwlQDDwSbgffGVNjfgjNtVbcf
QlpDQFJdvdFqJdFpLvDFpLLnzZMnBMRRzMTqnrzqTRPznz
qRVRqBzgwqRpqRgVqQRPpQJJPrPhPGJnsGrCFdFJrZdG
ZvWDmMvmSvCndssrsJ
WcZcNWlcMjBQpzNTqVBp
DpLPZLDDlcgmDmhVgfgfWWRwhwwt
VrVMdbCrrBTjCMQQtMwQNSqMQW
VCBHdJHdvrrFsbsdrBJTdTzZcpmZGDGPlmzmlccFDZDn"""

open System

let array = input.Split "\n"

// Q1

let parseFirst (input: string) =
    array
    |> Array.map (fun x -> x[0 .. x.Length / 2 - 1], x[x.Length / 2 .. x.Length])
    |> Array.map (fun (arr1, arr2) -> (Set arr1, Set arr2) ||> Set.intersect |> Seq.head)
    |> Array.map (fun arr ->
        match arr with
        | x when x |> Char.IsLower -> int x - 96
        | x when x |> Char.IsUpper -> int x - 38
        | _ -> 0)
    |> Array.sum

// Q2

let parseSecond (input: string) =
    array
    |> Array.mapFold
        (fun (state: string list) (arr: string) ->
            match state with
            | state when state.Length = 2 -> Some(arr :: state), []
            | _ -> None, arr :: state)
        []
    |> fst
    |> Array.filter ((<>) None)
    |> Array.map (fun lst ->
        Set.intersectMany (lst.Value |> List.map (fun x -> Set(x.Trim())))
        |> Set.toArray
        |> Array.head)
    |> Array.map (fun chr ->
        match chr with
        | x when x |> Char.IsLower -> int x - 96
        | x when x |> Char.IsUpper -> int x - 38
        | _ -> 0)
    |> Array.sum

printfn $"{(parseFirst input)}"
printfn $"{(parseSecond input)}"
